<template>
  <div class="w-full mx-auto lg:w-[65.95%]">
    <div class="container py-4 mx-auto">
      <el-card class="border-slate-100" :body-style="{ padding: '0px' }">
        <div class="card-header px-6 py-5">
          <h3>Headings</h3>
        </div>
        <p class="break-normal text-slate-500 px-4"></p>
        <div class="p-6">
          <div
            class="grid grid-cols-1 grid-flow-row md:grid-cols-2 md:gap-x-7 lg:grid-cols-2 lg:gap-x-7 lg:gap-y-2 xl:grid-cols-4 xl:gap-x-7 xl:gap-y-0.5"
          >
            <div class="block" v-for="(icon, key) in icons" :key="key">
              <el-button>
                <el-icon>
                  <component :is="icon.icon" />
                </el-icon>
                <span>{{ icon.name }}</span>
              </el-button>
            </div>
          </div>
        </div>
      </el-card>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import {
  ThumbUpIcon,
  AcademicCapIcon,
  AdjustmentsIcon,
  AnnotationIcon,
  ArchiveIcon,
  ArrowCircleDownIcon,
  ArrowCircleLeftIcon,
  ArrowCircleRightIcon,
  ArrowCircleUpIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowNarrowDownIcon,
  ArrowNarrowLeftIcon,
  ArrowNarrowRightIcon,
  ArrowNarrowUpIcon,
  ArrowRightIcon,
  ArrowSmDownIcon,
  ArrowSmLeftIcon,
  ArrowSmRightIcon,
  ArrowSmUpIcon,
  ArrowUpIcon,
  ArrowsExpandIcon,
  AtSymbolIcon,
  BackspaceIcon,
  BadgeCheckIcon,
  BanIcon,
  BeakerIcon,
  BellIcon,
  BookOpenIcon,
  BookmarkAltIcon,
  BookmarkIcon,
  BriefcaseIcon,
  CakeIcon,
  CalculatorIcon,
  CalendarIcon,
  CameraIcon,
  CashIcon,
  ChartBarIcon,
  ChartPieIcon,
  ChartSquareBarIcon,
  ChatAlt2Icon,
  ChatAltIcon,
  ChatIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDoubleDownIcon,
  ChevronDoubleLeftIcon,
  ChevronDoubleRightIcon,
  ChevronDoubleUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChipIcon,
  ClipboardCheckIcon,
  ClipboardCopyIcon,
  ClipboardIcon,
  ClipboardListIcon,
  ClockIcon,
  CloudDownloadIcon,
  CloudIcon,
  CloudUploadIcon,
  CodeIcon,
  CogIcon,
  CollectionIcon,
  ColorSwatchIcon,
  CreditCardIcon,
  CubeIcon,
  CubeTransparentIcon,
  CurrencyBangladeshiIcon,
  CurrencyDollarIcon,
  CurrencyEuroIcon,
  CurrencyPoundIcon,
  CurrencyRupeeIcon,
  CurrencyYenIcon,
  CursorClickIcon,
  DatabaseIcon,
  DesktopComputerIcon,
  DeviceMobileIcon,
  DeviceTabletIcon,
  DocumentAddIcon,
  DocumentDownloadIcon,
  DocumentDuplicateIcon,
  DocumentIcon,
  DocumentRemoveIcon,
  DocumentReportIcon,
  DocumentSearchIcon,
  DocumentTextIcon,
  DotsCircleHorizontalIcon,
  DotsHorizontalIcon,
  DotsVerticalIcon,
  DownloadIcon,
  DuplicateIcon,
  EmojiHappyIcon,
  EmojiSadIcon,
  ExclamationCircleIcon,
  ExclamationIcon,
  ExternalLinkIcon,
  EyeIcon,
  EyeOffIcon,
  FastForwardIcon,
  FilmIcon,
  FilterIcon,
  FingerPrintIcon,
  FireIcon,
  FlagIcon,
  FolderAddIcon,
  FolderDownloadIcon,
  FolderIcon,
  FolderOpenIcon,
  FolderRemoveIcon,
  GiftIcon,
  GlobeAltIcon,
  GlobeIcon,
  HandIcon,
  HashtagIcon,
  HeartIcon,
  HomeIcon,
  IdentificationIcon,
  InboxIcon,
  InboxInIcon,
  InformationCircleIcon,
  KeyIcon,
  LibraryIcon,
  LightBulbIcon,
  LightningBoltIcon,
  LinkIcon,
  LocationMarkerIcon,
  LockClosedIcon,
  LockOpenIcon,
  LoginIcon,
  LogoutIcon,
  MailIcon,
  MailOpenIcon,
  MapIcon,
  MenuAlt1Icon,
  MenuAlt2Icon,
  MenuAlt3Icon,
  MenuAlt4Icon,
  MenuIcon,
  MicrophoneIcon,
  MinusCircleIcon,
  MinusIcon,
  MinusSmIcon,
  MoonIcon,
  MusicNoteIcon,
  NewspaperIcon,
  OfficeBuildingIcon,
  PaperAirplaneIcon,
  PaperClipIcon,
  PauseIcon,
  PencilAltIcon,
  PencilIcon,
  PhoneIcon,
  PhoneIncomingIcon,
  PhoneMissedCallIcon,
  PhoneOutgoingIcon,
  PhotographIcon,
  PlayIcon,
  PlusCircleIcon,
  PlusIcon,
  PlusSmIcon,
  PresentationChartBarIcon,
  PresentationChartLineIcon,
  PrinterIcon,
  PuzzleIcon,
  QrcodeIcon,
  QuestionMarkCircleIcon,
  ReceiptRefundIcon,
  ReceiptTaxIcon,
  RefreshIcon,
  ReplyIcon,
  RewindIcon,
  RssIcon,
  SaveAsIcon,
  SaveIcon,
  ScaleIcon,
  ScissorsIcon,
  SearchCircleIcon,
  SearchIcon,
  SelectorIcon,
  ServerIcon,
  ShareIcon,
  ShieldCheckIcon,
  ShieldExclamationIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SortAscendingIcon,
  SortDescendingIcon,
  SparklesIcon,
  SpeakerphoneIcon,
  StarIcon,
  StatusOfflineIcon,
  StatusOnlineIcon,
  StopIcon,
  SunIcon,
  SupportIcon,
  SwitchHorizontalIcon,
  SwitchVerticalIcon,
  TableIcon,
  TagIcon,
  TemplateIcon,
  TerminalIcon,
  ThumbDownIcon,
  TicketIcon,
  TranslateIcon,
  TrashIcon,
  TrendingDownIcon,
  TrendingUpIcon,
  TruckIcon,
  UploadIcon,
  UserAddIcon,
  UserCircleIcon,
  UserGroupIcon,
  UserIcon,
  UserRemoveIcon,
  UsersIcon,
  VariableIcon,
  VideoCameraIcon,
  ViewBoardsIcon,
  ViewGridAddIcon,
  ViewGridIcon,
  ViewListIcon,
  VolumeOffIcon,
  VolumeUpIcon,
  WifiIcon,
  XCircleIcon,
  XIcon,
  ZoomInIcon,
  ZoomOutIcon,
} from '@heroicons/vue/solid'

export default defineComponent({
  components: {
    ThumbUpIcon,
    AcademicCapIcon,
    AdjustmentsIcon,
    AnnotationIcon,
    ArchiveIcon,
    ArrowCircleDownIcon,
    ArrowCircleLeftIcon,
    ArrowCircleRightIcon,
    ArrowCircleUpIcon,
    ArrowDownIcon,
    ArrowLeftIcon,
    ArrowNarrowDownIcon,
    ArrowNarrowLeftIcon,
    ArrowNarrowRightIcon,
    ArrowNarrowUpIcon,
    ArrowRightIcon,
    ArrowSmDownIcon,
    ArrowSmLeftIcon,
    ArrowSmRightIcon,
    ArrowSmUpIcon,
    ArrowUpIcon,
    ArrowsExpandIcon,
    AtSymbolIcon,
    BackspaceIcon,
    BadgeCheckIcon,
    BanIcon,
    BeakerIcon,
    BellIcon,
    BookOpenIcon,
    BookmarkAltIcon,
    BookmarkIcon,
    BriefcaseIcon,
    CakeIcon,
    CalculatorIcon,
    CalendarIcon,
    CameraIcon,
    CashIcon,
    ChartBarIcon,
    ChartPieIcon,
    ChartSquareBarIcon,
    ChatAlt2Icon,
    ChatAltIcon,
    ChatIcon,
    CheckCircleIcon,
    CheckIcon,
    ChevronDoubleDownIcon,
    ChevronDoubleLeftIcon,
    ChevronDoubleRightIcon,
    ChevronDoubleUpIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpIcon,
    ChipIcon,
    ClipboardCheckIcon,
    ClipboardCopyIcon,
    ClipboardIcon,
    ClipboardListIcon,
    ClockIcon,
    CloudDownloadIcon,
    CloudIcon,
    CloudUploadIcon,
    CodeIcon,
    CogIcon,
    CollectionIcon,
    ColorSwatchIcon,
    CreditCardIcon,
    CubeIcon,
    CubeTransparentIcon,
    CurrencyBangladeshiIcon,
    CurrencyDollarIcon,
    CurrencyEuroIcon,
    CurrencyPoundIcon,
    CurrencyRupeeIcon,
    CurrencyYenIcon,
    CursorClickIcon,
    DatabaseIcon,
    DesktopComputerIcon,
    DeviceMobileIcon,
    DeviceTabletIcon,
    DocumentAddIcon,
    DocumentDownloadIcon,
    DocumentDuplicateIcon,
    DocumentIcon,
    DocumentRemoveIcon,
    DocumentReportIcon,
    DocumentSearchIcon,
    DocumentTextIcon,
    DotsCircleHorizontalIcon,
    DotsHorizontalIcon,
    DotsVerticalIcon,
    DownloadIcon,
    DuplicateIcon,
    EmojiHappyIcon,
    EmojiSadIcon,
    ExclamationCircleIcon,
    ExclamationIcon,
    ExternalLinkIcon,
    EyeIcon,
    EyeOffIcon,
    FastForwardIcon,
    FilmIcon,
    FilterIcon,
    FingerPrintIcon,
    FireIcon,
    FlagIcon,
    FolderAddIcon,
    FolderDownloadIcon,
    FolderIcon,
    FolderOpenIcon,
    FolderRemoveIcon,
    GiftIcon,
    GlobeAltIcon,
    GlobeIcon,
    HandIcon,
    HashtagIcon,
    HeartIcon,
    HomeIcon,
    IdentificationIcon,
    InboxIcon,
    InboxInIcon,
    InformationCircleIcon,
    KeyIcon,
    LibraryIcon,
    LightBulbIcon,
    LightningBoltIcon,
    LinkIcon,
    LocationMarkerIcon,
    LockClosedIcon,
    LockOpenIcon,
    LoginIcon,
    LogoutIcon,
    MailIcon,
    MailOpenIcon,
    MapIcon,
    MenuAlt1Icon,
    MenuAlt2Icon,
    MenuAlt3Icon,
    MenuAlt4Icon,
    MenuIcon,
    MicrophoneIcon,
    MinusCircleIcon,
    MinusIcon,
    MinusSmIcon,
    MoonIcon,
    MusicNoteIcon,
    NewspaperIcon,
    OfficeBuildingIcon,
    PaperAirplaneIcon,
    PaperClipIcon,
    PauseIcon,
    PencilAltIcon,
    PencilIcon,
    PhoneIcon,
    PhoneIncomingIcon,
    PhoneMissedCallIcon,
    PhoneOutgoingIcon,
    PhotographIcon,
    PlayIcon,
    PlusCircleIcon,
    PlusIcon,
    PlusSmIcon,
    PresentationChartBarIcon,
    PresentationChartLineIcon,
    PrinterIcon,
    PuzzleIcon,
    QrcodeIcon,
    QuestionMarkCircleIcon,
    ReceiptRefundIcon,
    ReceiptTaxIcon,
    RefreshIcon,
    ReplyIcon,
    RewindIcon,
    RssIcon,
    SaveAsIcon,
    SaveIcon,
    ScaleIcon,
    ScissorsIcon,
    SearchCircleIcon,
    SearchIcon,
    SelectorIcon,
    ServerIcon,
    ShareIcon,
    ShieldCheckIcon,
    ShieldExclamationIcon,
    ShoppingBagIcon,
    ShoppingCartIcon,
    SortAscendingIcon,
    SortDescendingIcon,
    SparklesIcon,
    SpeakerphoneIcon,
    StarIcon,
    StatusOfflineIcon,
    StatusOnlineIcon,
    StopIcon,
    SunIcon,
    SupportIcon,
    SwitchHorizontalIcon,
    SwitchVerticalIcon,
    TableIcon,
    TagIcon,
    TemplateIcon,
    TerminalIcon,
    ThumbDownIcon,
    TicketIcon,
    TranslateIcon,
    TrashIcon,
    TrendingDownIcon,
    TrendingUpIcon,
    TruckIcon,
    UploadIcon,
    UserAddIcon,
    UserCircleIcon,
    UserGroupIcon,
    UserIcon,
    UserRemoveIcon,
    UsersIcon,
    VariableIcon,
    VideoCameraIcon,
    ViewBoardsIcon,
    ViewGridAddIcon,
    ViewGridIcon,
    ViewListIcon,
    VolumeOffIcon,
    VolumeUpIcon,
    WifiIcon,
    XCircleIcon,
    XIcon,
    ZoomInIcon,
    ZoomOutIcon,
  },
  setup() {
    const icons = [
      { name: 'ThumbUpIcon', icon: ThumbUpIcon },
      { name: 'AcademicCapIcon', icon: AcademicCapIcon },
      { name: 'AdjustmentsIcon', icon: AdjustmentsIcon },
      { name: 'AnnotationIcon', icon: AnnotationIcon },
      { name: 'ArchiveIcon', icon: ArchiveIcon },
      { name: 'ArrowCircleDownIcon', icon: ArrowCircleDownIcon },
      { name: 'ArrowCircleLeftIcon', icon: ArrowCircleLeftIcon },
      { name: 'ArrowCircleRightIcon', icon: ArrowCircleRightIcon },
      { name: 'ArrowCircleUpIcon', icon: ArrowCircleUpIcon },
      { name: 'ArrowDownIcon', icon: ArrowDownIcon },
      { name: 'ArrowLeftIcon', icon: ArrowLeftIcon },
      { name: 'ArrowNarrowDownIcon', icon: ArrowNarrowDownIcon },
      { name: 'ArrowNarrowLeftIcon', icon: ArrowNarrowLeftIcon },
      { name: 'ArrowNarrowRightIcon', icon: ArrowNarrowRightIcon },
      { name: 'ArrowNarrowUpIcon', icon: ArrowNarrowUpIcon },
      { name: 'ArrowRightIcon', icon: ArrowRightIcon },
      { name: 'ArrowSmDownIcon', icon: ArrowSmDownIcon },
      { name: 'ArrowSmLeftIcon', icon: ArrowSmLeftIcon },
      { name: 'ArrowSmRightIcon', icon: ArrowSmRightIcon },
      { name: 'ArrowSmUpIcon', icon: ArrowSmUpIcon },
      { name: 'ArrowUpIcon', icon: ArrowUpIcon },
      { name: 'ArrowsExpandIcon', icon: ArrowsExpandIcon },
      { name: 'AtSymbolIcon', icon: AtSymbolIcon },
      { name: 'BackspaceIcon', icon: BackspaceIcon },
      { name: 'BadgeCheckIcon', icon: BadgeCheckIcon },
      { name: 'BanIcon', icon: BanIcon },
      { name: 'BeakerIcon', icon: BeakerIcon },
      { name: 'BellIcon', icon: BellIcon },
      { name: 'BookOpenIcon', icon: BookOpenIcon },
      { name: 'BookmarkAltIcon', icon: BookmarkAltIcon },
      { name: 'BookmarkIcon', icon: BookmarkIcon },
      { name: 'BriefcaseIcon', icon: BriefcaseIcon },
      { name: 'CakeIcon', icon: CakeIcon },
      { name: 'CalculatorIcon', icon: CalculatorIcon },
      { name: 'CalendarIcon', icon: CalendarIcon },
      { name: 'CameraIcon', icon: CameraIcon },
      { name: 'CashIcon', icon: CashIcon },
      { name: 'ChartBarIcon', icon: ChartBarIcon },
      { name: 'ChartPieIcon', icon: ChartPieIcon },
      { name: 'ChartSquareBarIcon', icon: ChartSquareBarIcon },
      { name: 'ChatAlt2Icon', icon: ChatAlt2Icon },
      { name: 'ChatAltIcon', icon: ChatAltIcon },
      { name: 'ChatIcon', icon: ChatIcon },
      { name: 'CheckCircleIcon', icon: CheckCircleIcon },
      { name: 'CheckIcon', icon: CheckIcon },
      { name: 'ChevronDoubleDownIcon', icon: ChevronDoubleDownIcon },
      { name: 'ChevronDoubleLeftIcon', icon: ChevronDoubleLeftIcon },
      { name: 'ChevronDoubleRightIcon', icon: ChevronDoubleRightIcon },
      { name: 'ChevronDoubleUpIcon', icon: ChevronDoubleUpIcon },
      { name: 'ChevronDownIcon', icon: ChevronDownIcon },
      { name: 'ChevronLeftIcon', icon: ChevronLeftIcon },
      { name: 'ChevronRightIcon', icon: ChevronRightIcon },
      { name: 'ChevronUpIcon', icon: ChevronUpIcon },
      { name: 'ChipIcon', icon: ChipIcon },
      { name: 'ClipboardCheckIcon', icon: ClipboardCheckIcon },
      { name: 'ClipboardCopyIcon', icon: ClipboardCopyIcon },
      { name: 'ClipboardIcon', icon: ClipboardIcon },
      { name: 'ClipboardListIcon', icon: ClipboardListIcon },
      { name: 'ClockIcon', icon: ClockIcon },
      { name: 'CloudDownloadIcon', icon: CloudDownloadIcon },
      { name: 'CloudIcon', icon: CloudIcon },
      { name: 'CloudUploadIcon', icon: CloudUploadIcon },
      { name: 'CodeIcon', icon: CodeIcon },
      { name: 'CogIcon', icon: CogIcon },
      { name: 'CollectionIcon', icon: CollectionIcon },
      { name: 'ColorSwatchIcon', icon: ColorSwatchIcon },
      { name: 'CreditCardIcon', icon: CreditCardIcon },
      { name: 'CubeIcon', icon: CubeIcon },
      { name: 'CubeTransparentIcon', icon: CubeTransparentIcon },
      { name: 'CurrencyBangladeshiIcon', icon: CurrencyBangladeshiIcon },
      { name: 'CurrencyDollarIcon', icon: CurrencyDollarIcon },
      { name: 'CurrencyEuroIcon', icon: CurrencyEuroIcon },
      { name: 'CurrencyPoundIcon', icon: CurrencyPoundIcon },
      { name: 'CurrencyRupeeIcon', icon: CurrencyRupeeIcon },
      { name: 'CurrencyYenIcon', icon: CurrencyYenIcon },
      { name: 'CursorClickIcon', icon: CursorClickIcon },
      { name: 'DatabaseIcon', icon: DatabaseIcon },
      { name: 'DesktopComputerIcon', icon: DesktopComputerIcon },
      { name: 'DeviceMobileIcon', icon: DeviceMobileIcon },
      { name: 'DeviceTabletIcon', icon: DeviceTabletIcon },
      { name: 'DocumentAddIcon', icon: DocumentAddIcon },
      { name: 'DocumentDownloadIcon', icon: DocumentDownloadIcon },
      { name: 'DocumentDuplicateIcon', icon: DocumentDuplicateIcon },
      { name: 'DocumentIcon', icon: DocumentIcon },
      { name: 'DocumentRemoveIcon', icon: DocumentRemoveIcon },
      { name: 'DocumentReportIcon', icon: DocumentReportIcon },
      { name: 'DocumentSearchIcon', icon: DocumentSearchIcon },
      { name: 'DocumentTextIcon', icon: DocumentTextIcon },
      { name: 'DotsCircleHorizontalIcon', icon: DotsCircleHorizontalIcon },
      { name: 'DotsHorizontalIcon', icon: DotsHorizontalIcon },
      { name: 'DotsVerticalIcon', icon: DotsVerticalIcon },
      { name: 'DownloadIcon', icon: DownloadIcon },
      { name: 'DuplicateIcon', icon: DuplicateIcon },
      { name: 'EmojiHappyIcon', icon: EmojiHappyIcon },
      { name: 'EmojiSadIcon', icon: EmojiSadIcon },
      { name: 'ExclamationCircleIcon', icon: ExclamationCircleIcon },
      { name: 'ExclamationIcon', icon: ExclamationIcon },
      { name: 'ExternalLinkIcon', icon: ExternalLinkIcon },
      { name: 'EyeIcon', icon: EyeIcon },
      { name: 'EyeOffIcon', icon: EyeOffIcon },
      { name: 'FastForwardIcon', icon: FastForwardIcon },
      { name: 'FilmIcon', icon: FilmIcon },
      { name: 'FilterIcon', icon: FilterIcon },
      { name: 'FingerPrintIcon', icon: FingerPrintIcon },
      { name: 'FireIcon', icon: FireIcon },
      { name: 'FlagIcon', icon: FlagIcon },
      { name: 'FolderAddIcon', icon: FolderAddIcon },
      { name: 'FolderDownloadIcon', icon: FolderDownloadIcon },
      { name: 'FolderIcon', icon: FolderIcon },
      { name: 'FolderOpenIcon', icon: FolderOpenIcon },
      { name: 'FolderRemoveIcon', icon: FolderRemoveIcon },
      { name: 'GiftIcon', icon: GiftIcon },
      { name: 'GlobeAltIcon', icon: GlobeAltIcon },
      { name: 'GlobeIcon', icon: GlobeIcon },
      { name: 'HandIcon', icon: HandIcon },
      { name: 'HashtagIcon', icon: HashtagIcon },
      { name: 'HeartIcon', icon: HeartIcon },
      { name: 'HomeIcon', icon: HomeIcon },
      { name: 'IdentificationIcon', icon: IdentificationIcon },
      { name: 'InboxIcon', icon: InboxIcon },
      { name: 'InboxInIcon', icon: InboxInIcon },
      { name: 'InformationCircleIcon', icon: InformationCircleIcon },
      { name: 'KeyIcon', icon: KeyIcon },
      { name: 'LibraryIcon', icon: LibraryIcon },
      { name: 'LightBulbIcon', icon: LightBulbIcon },
      { name: 'LightningBoltIcon', icon: LightningBoltIcon },
      { name: 'LinkIcon', icon: LinkIcon },
      { name: 'LocationMarkerIcon', icon: LocationMarkerIcon },
      { name: 'LockClosedIcon', icon: LockClosedIcon },
      { name: 'LockOpenIcon', icon: LockOpenIcon },
      { name: 'LoginIcon', icon: LoginIcon },
      { name: 'LogoutIcon', icon: LogoutIcon },
      { name: 'MailIcon', icon: MailIcon },
      { name: 'MailOpenIcon', icon: MailOpenIcon },
      { name: 'MapIcon', icon: MapIcon },
      { name: 'MenuAlt1Icon', icon: MenuAlt1Icon },
      { name: 'MenuAlt2Icon', icon: MenuAlt2Icon },
      { name: 'MenuAlt3Icon', icon: MenuAlt3Icon },
      { name: 'MenuAlt4Icon', icon: MenuAlt4Icon },
      { name: 'MenuIcon', icon: MenuIcon },
      { name: 'MicrophoneIcon', icon: MicrophoneIcon },
      { name: 'MinusCircleIcon', icon: MinusCircleIcon },
      { name: 'MinusIcon', icon: MinusIcon },
      { name: 'MinusSmIcon', icon: MinusSmIcon },
      { name: 'MoonIcon', icon: MoonIcon },
      { name: 'MusicNoteIcon', icon: MusicNoteIcon },
      { name: 'NewspaperIcon', icon: NewspaperIcon },
      { name: 'OfficeBuildingIcon', icon: OfficeBuildingIcon },
      { name: 'PaperAirplaneIcon', icon: PaperAirplaneIcon },
      { name: 'PaperClipIcon', icon: PaperClipIcon },
      { name: 'PauseIcon', icon: PauseIcon },
      { name: 'PencilAltIcon', icon: PencilAltIcon },
      { name: 'PencilIcon', icon: PencilIcon },
      { name: 'PhoneIcon', icon: PhoneIcon },
      { name: 'PhoneIncomingIcon', icon: PhoneIncomingIcon },
      { name: 'PhoneMissedCallIcon', icon: PhoneMissedCallIcon },
      { name: 'PhoneOutgoingIcon', icon: PhoneOutgoingIcon },
      { name: 'PhotographIcon', icon: PhotographIcon },
      { name: 'PlayIcon', icon: PlayIcon },
      { name: 'PlusCircleIcon', icon: PlusCircleIcon },
      { name: 'PlusIcon', icon: PlusIcon },
      { name: 'PlusSmIcon', icon: PlusSmIcon },
      { name: 'PresentationChartBarIcon', icon: PresentationChartBarIcon },
      { name: 'PresentationChartLineIcon', icon: PresentationChartLineIcon },
      { name: 'PrinterIcon', icon: PrinterIcon },
      { name: 'PuzzleIcon', icon: PuzzleIcon },
      { name: 'QrcodeIcon', icon: QrcodeIcon },
      { name: 'QuestionMarkCircleIcon', icon: QuestionMarkCircleIcon },
      { name: 'ReceiptRefundIcon', icon: ReceiptRefundIcon },
      { name: 'ReceiptTaxIcon', icon: ReceiptTaxIcon },
      { name: 'RefreshIcon', icon: RefreshIcon },
      { name: 'ReplyIcon', icon: ReplyIcon },
      { name: 'RewindIcon', icon: RewindIcon },
      { name: 'RssIcon', icon: RssIcon },
      { name: 'SaveAsIcon', icon: SaveAsIcon },
      { name: 'SaveIcon', icon: SaveIcon },
      { name: 'ScaleIcon', icon: ScaleIcon },
      { name: 'ScissorsIcon', icon: ScissorsIcon },
      { name: 'SearchCircleIcon', icon: SearchCircleIcon },
      { name: 'SearchIcon', icon: SearchIcon },
      { name: 'SelectorIcon', icon: SelectorIcon },
      { name: 'ServerIcon', icon: ServerIcon },
      { name: 'ShareIcon', icon: ShareIcon },
      { name: 'ShieldCheckIcon', icon: ShieldCheckIcon },
      { name: 'ShieldExclamationIcon', icon: ShieldExclamationIcon },
      { name: 'ShoppingBagIcon', icon: ShoppingBagIcon },
      { name: 'ShoppingCartIcon', icon: ShoppingCartIcon },
      { name: 'SortAscendingIcon', icon: SortAscendingIcon },
      { name: 'SortDescendingIcon', icon: SortDescendingIcon },
      { name: 'SparklesIcon', icon: SparklesIcon },
      { name: 'SpeakerphoneIcon', icon: SpeakerphoneIcon },
      { name: 'StarIcon', icon: StarIcon },
      { name: 'StatusOfflineIcon', icon: StatusOfflineIcon },
      { name: 'StatusOnlineIcon', icon: StatusOnlineIcon },
      { name: 'StopIcon', icon: StopIcon },
      { name: 'SunIcon', icon: SunIcon },
      { name: 'SupportIcon', icon: SupportIcon },
      { name: 'SwitchHorizontalIcon', icon: SwitchHorizontalIcon },
      { name: 'SwitchVerticalIcon', icon: SwitchVerticalIcon },
      { name: 'TableIcon', icon: TableIcon },
      { name: 'TagIcon', icon: TagIcon },
      { name: 'TemplateIcon', icon: TemplateIcon },
      { name: 'TerminalIcon', icon: TerminalIcon },
      { name: 'ThumbDownIcon', icon: ThumbDownIcon },
      { name: 'TicketIcon', icon: TicketIcon },
      { name: 'TranslateIcon', icon: TranslateIcon },
      { name: 'TrashIcon', icon: TrashIcon },
      { name: 'TrendingDownIcon', icon: TrendingDownIcon },
      { name: 'TrendingUpIcon', icon: TrendingUpIcon },
      { name: 'TruckIcon', icon: TruckIcon },
      { name: 'UploadIcon', icon: UploadIcon },
      { name: 'UserAddIcon', icon: UserAddIcon },
      { name: 'UserCircleIcon', icon: UserCircleIcon },
      { name: 'UserGroupIcon', icon: UserGroupIcon },
      { name: 'UserIcon', icon: UserIcon },
      { name: 'UserRemoveIcon', icon: UserRemoveIcon },
      { name: 'UsersIcon', icon: UsersIcon },
      { name: 'VariableIcon', icon: VariableIcon },
      { name: 'VideoCameraIcon', icon: VideoCameraIcon },
      { name: 'ViewBoardsIcon', icon: ViewBoardsIcon },
      { name: 'ViewGridAddIcon', icon: ViewGridAddIcon },
      { name: 'ViewGridIcon', icon: ViewGridIcon },
      { name: 'ViewListIcon', icon: ViewListIcon },
      { name: 'VolumeOffIcon', icon: VolumeOffIcon },
      { name: 'VolumeUpIcon', icon: VolumeUpIcon },
      { name: 'WifiIcon', icon: WifiIcon },
      { name: 'XCircleIcon', icon: XCircleIcon },
      { name: 'XIcon', icon: XIcon },
      { name: 'ZoomInIcon', icon: ZoomInIcon },
      { name: 'ZoomOutIcon', icon: ZoomOutIcon },
    ]

    // expose to template and other options API hooks
    return {
      icons,
    }
  },
})
</script>

<style lang="scss" scoped>
body {
  .el-button {
    @apply bg-icon 
    py-9 
    px-6
    flex 
    w-full 
    text-primary 
    text-base 
    font-normal 
    leading-5 
    rounded-md 
    border-transparent
    text-left 
    items-center 
    align-middle 
    no-underline 
    my-2 
    hover:border-transparent 
    focus:outline
    focus:outline-2
    focus:outline-webkit 
    shadow-none
    drop-shadow-none
    translate-x-0
    translate-y-0
    hover:border-opacity-95
    hover:bg-white 
    hover:text-primary
    hover:shadow-medium
    hover:drop-shadow
    #{!important};
  }
  .el-button > :deep(span) {
    @apply w-full;
  }
  .el-button [class*='el-icon'] + span {
    @apply w-full inline-block text-sm text-left font-normal leading-6 overflow-hidden text-ellipsis whitespace-nowrap;
  }
  .el-button .el-icon {
    @apply text-2xl text-primary-blue inline-block ml-[-8px] mr-0.5 #{!important};
  }
  .card-typography {
    @apply bg-white break-words mt-2 mb-7 shadow rounded-lg flex flex-col;
  }
  .card-header {
    @apply p-5 border-b border-primary-white;
  }
  .row {
    @apply my-8 w-full h-auto;
  }
  .title {
    @apply uppercase text-80 font-semibold text-muted;
  }
  .medium {
    @apply flex flex-col md:flex-row md:justify-center md:items-center;
  }
}
</style>
